### ISSUE TITLE
Compile error due to case sensitive on Linux

### ISSUE THREAD

**Issue by KuribohG** [pablode/gatling#3]
Thank you for this awesome project! I think this is a really good starting point to learn USD & Hydra. This project helped me so much!

There is a compile error on Linux. Since Linux has case sensitive file system, `shadergen.*` is not the same as `ShaderGen.*`. This caused CMake error and C++ compile error (because compiler cannot find `shadergen.h` header).

Here is my solution for this error:
- Rename `shadergen.h` and `shadergen.cpp` to `ShaderGen.h` and `ShaderGen.cpp`
- In `gatling/src/gi/src/gi.cpp`, modify the included file name

**Comment by pablode** [comment]
Hi - I'm glad this project helped you!
Thanks for the report; I've fixed the issue like you suggested in commit [1f0b539](https://github.com/pablode/gatling/commit/1f0b539a4985c9d039536894b2b58ad83be635ca).
