### ISSUE TITLE
About the assets in the usd-assets repository

### ISSUE THREAD

**Issue by aaronmack** [pablode/gatling#9]
The assets in the `usd-assets` repository don't seem to come with texture, can you simply demonstrate one for viewing?

repository: https://github.com/pablode/usd-assets

Be deeply grateful!

Aaron

**Comment by pablode** [comment]
Texture support is still work-in-progress, but I expect it to be finished soon.

I will then add multiple assets with textures.

For now, USD+MDL assets with textures should already be working - here are free examples from TurboSquid: https://www.turbosquid.com/omniverse-3D-models#free-models

**Comment by aaronmack** [comment]
So cool, thanks.
